### ISSUE TITLE
Implement on wayfarer

### ISSUE THREAD

**Issue by shama** [shama/base-router#2]
Implement using @yoshuawuyts https://github.com/yoshuawuyts/wayfarer

**Comment by shama** [comment]
I gave this a shot but I want to have an associated `model` with each route when registering. [routes](https://www.npmjs.com/package/routes) has a 2nd parameter when adding routes for it. Without it, I'd have to manage the route/model mapping myself which I feel would get cumbersome. So sticking with `routes` for now.

**Comment by yoshuawuyts** [comment]
I'm not sure I understand how it differs; looking at [`routes.addRoute()`](https://github.com/aaronblohowiak/routes.js/blob/master/index.js#L127) and [`base-router.route`()](https://github.com/shama/base-router/blob/master/index.js#L23)  it appears that the signature of `route, cb` is similar to `wayfarer`. Is there any way `wayfarer` can better support your use case?

**Comment by shama** [comment]
Oh sorry! I got confused by the api. I didn't realize `router.on(route, cb)` _creates_ new routes, instead of responding to an event as `.on()` typically does.

I still may not understand the API but the other issues are:
- I want to first see if a route matches first and issue an error otherwise.
- I want to supply arguments to the matched route's function.
- I want the return value of the matched route to know whether to resolve a `return`, `callback` or `promise`.
- I noticed the wayfarer uses ES6 features. It would be nice if the published version was compatible with platforms that don't yet support ES6.

**Comment by yoshuawuyts** [comment]
Whoops, I hope other people don't share your confusions. I'll take my time to review the docs and see if I can make them clearer. But to answer your issues:
- **errs**: I think having an error callback makes sense for `.emit()`. Ideally `wayfarer` would emit a `.on('error')` event, but I don't think it'll work well with the existing paths since it might conflict with a path called `error`. Though this can be worked around with by requiring leading slashes in paths. Which interface would you prefer?
- **args**: In the applications I build I generally use a dispatcher + actions & stores to pass state around; I haven't found any need to pass data through my router so I'm curious to hear what kind of arguments you'd like to provide.
- **return**: there is no concept of 'done' in `wayfarer`. This might again have to do that I use a dispatcher to move data around, and `wayfarer` solely to resolve paths.
- **es6**: es6 is only used in the examples since it looks nicely with `.on()`. There's a patch in the works that uses [`es6-symbol`](https://github.com/medikoo/es6-symbol), but the non-shim interface should run safely on any es5 environment.

I hope this answers your questions? I'm not sure how to resolve the data transport difference. Do you have any examples where you're doing that, I'm interested in seeing how you structure your apps.

**Comment by shama** [comment]
- **errs** I just need to know whether the router is handling the path or not (so the server can either 404 or hand off; the client would display an error ui).
- **args** I prefer a data down / events up approach. A route, to me, is where the data starts. The pathname and query string tell us which data is needed. Once we've gathered all the data we need for a given route, it gets passed down to the views. The views interact with the data and send events up. Those events are captured, data is modified (possibly stored / transitioned) and then sent back down to the views. I find this keeps the view modules generic and gives the end user great control over their app.
- **return** For simple things, I just `return`. Most of the time I'm using `xhr('/api/endpoint.json', function (err, res, body) { done(null, body) })` or `fs.readFile('page.md', done)` to get data but also frequently use promise based libs. `return fetch('/api/endpoint.json')` will be great once `fetch` shims get a bit better. Knowing when a route has failed/aborted or is loading is important so I can toggle the UI to indicate as needed.
- **es6** I was specifically referring to the use of `const` in the published code. Which would error on Node.js and IE atm.

An example user form that demonstrates the flow is like this:

``` js
var xhr = require('xhr')
var createRouter = require('base-router')
var createElement = require('base-element')
var createUserView = require('./lib/user-view.js')

// Create our views
var app = createElement(document.body)
var userView = createUserView()

// Define our router
var router = createRouter({
  '/prefs/:userid': function (params, done) {
    xhr('/api/users.json?id=' + params.userid, function (err, res, body) {
      if (err) return done(err)
      done(null, userView.render(body))
    })
  },
  '/saveprefs': function (params, done) {
    xhr({
      method: 'POST',
      uri: '/api/users.json?id=' + data.userid,
      json: params
    }, function (err, res, body) {
      if (err.statusCode === 422) {
        // Server says a field is invalid
        params.error = err.message
        router.transitionTo('/prefs/' + params.userid, params)
      } else {
        done(null, app.html('.success', 'User info saved!'))
      }
    })
  }
})

// Handle loading of routes
router.on('loading', function () {
  document.body.classList.add('loading')
})

// Handle the main rendering of the app
router.on('transition', function (route, view) {
  document.body.classList.remove('loading')
  app.render(function () {
    return app.html('.container', [
      linksView,
      view
    ])
  })
})

// When userView saves, transition to save the data
userView.addEventListener('save', function (data) {
  router.transitionTo('/saveprefs', data)
})

// Default route
router.transitionTo('/prefs/1')
```

If certain routes get heavy they are easy to offload:

``` js
var router = createRouter({
  '/stuff': require('./models/stuff.js')
})
```

Or if really needed, could be coupled with the views (but don't recommend for any element you plan on publishing as it would create a peer dep to base-router):

``` js
// app.js
let router = createRouter()
let username = new UsernameElement(document.body, router)
username.addEventListener('saved', () => {
  alert('Username saved!')
})

// username-element.js
class UsernameElement extends BaseElement {
  constructor (el, router) {
    super(el)
    this.router = router
    router.route('/user/:name', (params, done) => {
      this.render(params.name)
    })
    router.route('/users/save', (params, done) => {
      xhr({ uri: '/users/save', json: params }, () => {
        this.send('saved')
      })
    })
  }
  render (name) {
    return this.html('input.username', {
      onclick: (e) => {
        this.router.transitionTo('/users/save', { name: e.target.value })
      },
      value: name
    }, '')
  }
}
```

**Comment by shama** [comment]
It's also worth noting this flow is modeled after the parts I like from Ember and React... just greatly simplified :)

**Comment by yoshuawuyts** [comment]
I've been a bit busy yesterday; I'll take my time to answer your post tonight or tomorrow (CET). I'd very much like it _to be possible_ for `base-router` to be built on `wayfarer`.

**Comment by yoshuawuyts** [comment]
Glad this got in! :D Just as a lil' side note: `const` works in ~~`node>=0.8`~~ `node>=0.10`.

**Comment by shama** [comment]
Oh really? I didn't know that. I thought it was `>=0.12`. Thanks for the help!
