### ISSUE TITLE
Preventing page reload on link click

### ISSUE THREAD

**Issue by chinedufn** [shama/base-router#3]
Right now if you click a link your entire application reloads. Thoughts on having base-router prevent this by default? 

Something like:

``` js
  if (usePush) {
    function preventLinkReload(e) {
      if (e.target.tagName !== 'A') return
      e.preventDefault()
      self.transitionTo(e.target.pathname)
    }
    document.addEventListener('click', preventLinkReload, false)
    // etc
```

Will PR if there's interest ;)

**Comment by shama** [comment]
I think that should be handled by the user instead. As there are too many possibilities:
- Some links, ie `<a href="http://google.com">go to google.com</a>` should not be prevented
- Even with internal links, we can't assume the user always wants to use `transitionTo` for routing
- Other elements, besides `<a/>`, can trigger transitions too
- Users should retain control how elements propagate

The good news is it's fairly easy for users to implement. With base-element:

``` js
return this.html('a', {
  href: '/pathname',
  onclick: function (e) {
    e.preventDefault()
    router.transitionTo(e.target.href)
    // Or likely this element is nested, so we should this.send('transition', e.target.href)
    // then listen for that event to pass to the router.transitionTo
  }
}, 'go')
```

Or just using the browser API:

``` js
var a = document.createElement('a')
a.setAttribute('href', '/pathname')
a.addEventListener('click', function (e) {
  e.preventDefault()
  router.transitionTo(e.target.href)
}, false)
```

**Comment by chinedufn** [comment]
Great points thanks ;). Closing this.

Although I do think that one of these solutions should be added to the current [example](https://github.com/shama/base-router/blob/master/example.js) (or a new one). But that's another issue

**Comment by shama** [comment]
Yep! I agree. I should have more end to end examples soon.
