### ISSUE TITLE
route vs addRoute

### ISSUE THREAD

**Issue by chinedufn** [shama/base-router#8]
I'm thinking that [Router.route](https://github.com/shama/base-router/blob/master/index.js#L23) should be deprecated in favor of a new `Router.addRoute` and removed whenever v2 roles around.

Seems like it might make more sense, especially since `base-router` is depending on [routes](https://github.com/aaronblohowiak/routes.js) for now

**Comment by shama** [comment]
Why is `addRoute` a better name then `route`? I chose `route` because that is also the name used to define new routes with Ember and React. I thought I'd use a name that was already familiar to those users.

**Comment by chinedufn** [comment]
I don't use Ember or React so that's an interesting new point that I did not consider.

IMO `addRoute` is a better name because it actually indicates what is happening, whereas a name like `route` is semi-ambiguous and doesn't immediately tell you what is going on.

i.e. Am I adding a route? Switching to a new route? Manipulating the current route? Something else?

Would love to hear your closing thoughts

**Comment by shama** [comment]
I gave this more thought and think you're right that `addRoute` is less ambiguous. So I'm :+1: to this change.
